In [1]:
import pandas as pd

In [6]:
df = pd.read_csv(r"D:\DevTools\datasets\wine review data set\winemag-data-130k-v2.csv")
df.head(5)

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [63]:
print(type(df))
df['price'].dtype
variety_series = df['variety']
print(variety_series.index)
print(variety_series.values)

<class 'pandas.DataFrame'>
RangeIndex(start=0, stop=129971, step=1)
<ArrowStringArray>
[       'White Blend',     'Portuguese Red',         'Pinot Gris',
           'Riesling',         'Pinot Noir', 'Tempranillo-Merlot',
           'Frappato',     'Gewürztraminer',     'Gewürztraminer',
         'Pinot Gris',
 ...
           'Frappato',       'Nero d'Avola', 'Cabernet Sauvignon',
     'Gewürztraminer',         'Pinot Gris',           'Riesling',
         'Pinot Noir',     'Gewürztraminer',         'Pinot Gris',
     'Gewürztraminer']
Length: 129971, dtype: str

In [ ]:
wine_1 = pd.DataFrame({'name': ['Château Étoile', 'Bella Vista Riserva', 'Sunbreak Pinot'],
                      'country': ['France', 'Italy', 'USA'],
                      'points': [95, 92, 89]})
wine_1 = pd.DataFrame([{'name': 'Château Étoile', 'country': 'France', 'points': 95},
    {'name': 'Bella Vista Riserva', 'country': 'Italy', 'points': 92},
    {'name': 'Sunbreak Pinot', 'country': 'USA', 'points': 89}])
points_series = wine_1['points']
print(points_series)
print(type(points_series))

0    95
1    92
2    89
Name: points, dtype: int64
<class 'pandas.Series'>

In [62]:
df = pd.read_csv(r"D:\DevTools\datasets\wine review data set\winemag-data-130k-v2.csv")
df.head(10).to_csv('sample_wines.csv', index = False)
sample_wines = pd.read_csv(r'D:\DevTools\pandas-practice\sample_wines.csv')
sample_wines.head(10)

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
5,5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
6,6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
7,7,France,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach
8,8,Germany,Savory dried thyme notes accent sunnier flavor...,Shine,87,12.0,Rheinhessen,NaN,NaN,Anna Lee C. Iijima,NaN,Heinz Eifel 2013 Shine Gewürztraminer (Rheinhe...,Gewürztraminer,Heinz Eifel
9,9,France,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,Jean-Baptiste Adam

In [ ]:
print(df.index)
print(df.columns)
print(type(df.index))
print(type(df.columns))
df2 = df.set_index('title')
df2['country']

title
Nicosia 2013 Vulkà Bianco  (Etna)                                                                           Italy
Quinta dos Avidagos 2011 Avidagos Red (Douro)                                                            Portugal
Rainstorm 2013 Pinot Gris (Willamette Valley)                                                                  US
St. Julian 2013 Reserve Late Harvest Riesling (Lake Michigan Shore)                                            US
Sweet Cheeks 2012 Vintner's Reserve Wild Child Block Pinot Noir (Willamette Valley)                            US
                                                                                                           ...
Dr. H. Thanisch (Erben Müller-Burggraef) 2013 Brauneberger Juffer-Sonnenuhr Spätlese Riesling (Mosel)     Germany
Citation 2004 Pinot Noir (Oregon)                                                                              US
Domaine Gresser 2013 Kritt Gewurztraminer (Alsace)                                                         France
Domaine Marcel Deiss 2012 Pinot Gris (Alsace)                                                              France
Domaine Schoffit 2012 Lieu-dit Harth Cuvée Caroline Gewurztraminer (Alsace)                                France
Name: country, Length: 129971, dtype: str

In [40]:
df.head(10)
df.tail(3)
df.info()
df.shape
df.dtypes

<class 'pandas.DataFrame'>
RangeIndex: 129971 entries, 0 to 129970
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   country                129908 non-null  str
 1   description            129971 non-null  str
 2   designation            92506 non-null   str
 3   points                 129971 non-null  int64
 4   price                  120975 non-null  float64
 5   province               129908 non-null  str
 6   region_1               108724 non-null  str
 7   region_2               50511 non-null   str
 8   taster_name            103727 non-null  str
 9   taster_twitter_handle  98758 non-null   str
 10  title                  129971 non-null  str
 11  variety                129970 non-null  str
 12  winery                 129971 non-null  str
dtypes: float64(1), int64(1), str(11)
memory usage: 60.1 MB

country                      str
description                  str
designation                  str
points                     int64
price                    float64
province                     str
region_1                     str
region_2                     str
taster_name                  str
taster_twitter_handle        str
title                        str
variety                      str
winery                       str
dtype: object

In [61]:
df.describe(include='object')
print(df['points'].mean())
print(df['points'].median())  
#mean and median are near represents data is symmetrical
print(df['price'].min())
print(df['price'].max())
print(df['points'].std())

C:\Users\Surendar Reddy\AppData\Local\Temp\ipykernel_30816\2315559169.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

88.44713820775404
88.0
4.0
3300.0
3.0397302029160036

In [60]:
print(df.dtypes.unique())
df['points'].dtype  #int 64
df['points'] = df['points'].astype('float64')
print(df['points'].dtype)
print(df['country'].memory_usage())
#df['price'].astype('int64')  #error due to presence of missing values
print(df['country'].astype('category').memory_usage())

[<StringDtype(na_value=nan)> dtype('float64')]
float64
1639086
130773